# Generated by Django 3.0.2 on 2020-08-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='fecha_mod',
            field=models.CharField(max_length=10, verbose_name='FECHA_MODIFICACION'),
        ),
    ]
