# Generated by Django 3.0.2 on 2020-08-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='comentario',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='COMENTARIO'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='fecha_mod',
            field=models.DateTimeField(verbose_name='FECHA_MODIFICACION'),
        ),
    ]
