# Generated by Django 3.0.2 on 2020-08-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0002_auto_20200817_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='Nominas'),
            preserve_default=False,
        ),
    ]
