# Generated by Django 3.0.2 on 2020-08-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0002_auto_20200821_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='comentario',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='COMENTARIO'),
            preserve_default=False,
        ),
    ]
