# Generated by Django 3.0.2 on 2020-11-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0003_auto_20200821_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='fecha_pago',
            field=models.CharField(max_length=10, verbose_name='FECHA PAGO'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='importe_isr',
            field=models.FloatField(verbose_name='ISR TIM'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='isr_retim',
            field=models.FloatField(verbose_name='ISR_RETIMBRE'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='NOMBRE_NOMINA'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='num_xml',
            field=models.IntegerField(verbose_name='NUM XML'),
        ),
    ]
