# Generated by Django 3.0.2 on 2020-08-17 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0003_nomina_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomina',
            name='name',
        ),
        migrations.AlterModelTable(
            name='nomina',
            table='Nominas',
        ),
    ]
