# Generated by Django 3.0.2 on 2020-08-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0004_auto_20200817_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomina',
            name='isr_tim_retim',
        ),
        migrations.AddField(
            model_name='nomina',
            name='isr_retim',
            field=models.FloatField(default=1, verbose_name='ISR_TIM'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nomina',
            name='fecha_pago',
            field=models.CharField(max_length=10, verbose_name='FECHA_PAGO'),
        ),
    ]
