# Generated by Django 3.0.2 on 2020-08-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0005_auto_20200818_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='fecha_mod',
            field=models.DateTimeField(auto_now=True, verbose_name='FECHA_MODIFICACION'),
        ),
    ]
